//CRIAR UMA PASTA VAZIA

//DENTRO DELA CRIAR O PACKAGE.JSON
//NPM INIT NO TERMINAL

//CONFIGURA O PACKAGE E INSTALAR OS PACOTES
//npm install express
//npm install http-status
//npm install mysql2
//npm install sequelize

//PASTA src
//DENTRO DELA VAI FICAR OS ARQUIVOS E PASTAS DO PROJETO
//PASTAS: CONFIG, CONTROLLER, MODELS, DATABASE E ROUTES

//CRIAR O ARQUIVO MAIN.JS DENTRO DA PASTA SRC
//CONFIGURAR O PACKAGE.JSON

//CONFIGURAR O MAIN.JS

//CRIAR O ARQUIVO DE CONFIGURACAO NA PASTA CONFIG

//CRIAR OS CONTROLLERS DO NOSSO APP

//CRIAR O ARQUIVO DE BD - DATABASE

//CRIAR AS MODELS DO APP

//CRIAR AS ROTAS DO APP